title: Začínáme s Dockerem
baseURL: https://awfulthings.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs
googleAnalytics: UA-90823022-2

menu:
  main:
    - name: Nejnovější
      url: /
      weight: 10
    - name: Archiv
      identifier: post
      url: /post/
      weight: 20

params:
  description: Užitečné návody.
  authors: kisk

