title: Docker
baseURL: https://awfulthings.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs
googleAnalytics: UA-90823022-2

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

